<?php

/**
 * Implements hook_help().
 */
function social_contact_info_help($path, $arg) {
  switch ($path) {
  	// Main module help for the block module
    case 'admin/help#block':
      return '<p>' . t('Blocks are boxes of content rendered into an area, or region, of a web page. The default theme Bartik, for example, implements the regions "Sidebar first", "Sidebar second", "Featured", "Content", "Header", "Footer", etc., and a block may appear in any one of these areas. The <a href="@blocks">blocks administration page</a> provides a drag-and-drop interface for assigning a block to a region, and for controlling the order of blocks within regions.', array(
        '@blocks' => url('admin/structure/block'),
      )) . '</p>';
  }
}

/**
 * Implements hook_block_info().
 */
function social_contact_info_block_info() {
  $blocks['social_contact_info'] = array(
    'info'   => t('Social Contact Info'),
    'cache'  => DRUPAL_CACHE_PER_ROLE,
    'status' => TRUE,
    'region' => 'none',
  );
  return $blocks;
}

/**
 * Implements hook_block_configure().
 */
function social_contact_info_block_configure($delta = '') {
  // Declare $form array.
  $form = array();
  if ($delta == 'social_contact_info') {
    // Website contact information.
    $form['contact_detail'] = array(
      '#type' => 'fieldset',
      '#title' => t('Contact Information'),
  		'#collapsible' => FALSE,
  		'#collapsed' => FALSE,
  		'#description' => t('Contact information shows contact detail of the website. e.g. (Address, Phone, Email, etc..).'),
    );
    $form['contact_detail']['contact_title'] = array(
      '#type' => 'textfield',
      '#title' => t('Contact Title'),
      '#description' => t('This is contact title which helps to show contact title on top of the contact section. (This is optional.)'),
      '#attributes' => array(
        'placeholder' => t('Contact Title'),
      ),
      '#default_value' => variable_get('contact_title', ''),
    );
    $form['contact_detail']['contact_address'] = array(
    	'#type' => 'text_format',
    	'#title' => t('Address'),
    	'#resizable' => FALSE,
      '#format' => 'full_html',
    	'#default_value' => variable_get('contact_address', ''),
    );
    $form['contact_detail']['contact_email'] = array(
      '#type' => 'textfield',
      '#title' => t('Email'),
      '#description' => t('This is website email field which helps to show website email. (This is required.)'),
      '#attributes' => array(
        'placeholder' => t('email'),
      ),
      '#default_value' => variable_get('contact_email', ''),
      '#required' => TRUE,
    );
    $form['contact_detail']['contact_phone'] = array(
    	'#type' => 'textfield',
    	'#title' => t('Phone Number'),
    	'#description' => t('This is website phone number field which helps to show website phone number. (This is optional.)'),
    	'#attributes' => array(
        'placeholder' => t('Phone Number'),
      ),
    	'#default_value' => variable_get('contact_phone', ''),
    );
    $form['contact_detail']['contact_mobile'] = array(
      '#type' => 'textfield',
      '#title' => t('Mobile Number'),
      '#description' => t('This is website mobile number field which helps to show website mobile number. (This is optional.)'),
      '#attributes' => array(
        'placeholder' => t('Mobile Number'),
      ),
      '#default_value' => variable_get('contact_mobile', ''),
    );
     $form['contact_detail']['contact_fax'] = array(
      '#type' => 'textfield',
      '#title' => t('FAX'),
      '#description' => t('This is website fax number field which helps to show website fax number. (This is optional.)'),
      '#attributes' => array(
        'placeholder' => t('FAX'),
      ),
      '#default_value' => variable_get('contact_fax', ''),
    );
    // Website Social information.
    $form['social_detail'] = array(
      '#type' => 'fieldset',
      '#title' => t('Social Information'),
      '#collapsible' => FALSE,
      '#collapsed' => FALSE,
      '#description' => t('Social information shows social links of the website. e.g. (Facebook, LinkedIn, Twitter, etc..).'),
    );
    $form['social_detail']['social_title'] = array(
      '#type' => 'textfield',
      '#title' => t('Social Title'),
      '#description' => t('This is social title which helps to show social title on top of the social section. (This is optional.)'),
      '#attributes' => array(
        'placeholder' => t('Social Title'),
      ),
      '#default_value' => variable_get('social_title', ''),
    );
    $form['social_detail']['social_facebook'] = array(
      '#type' => 'textfield',
      '#title' => t('Facebook'),
      '#description' => t('Add your Facebook profile link here.'),
      '#attributes' => array(
        'class' => array('facebook'),
        'placeholder' => t('https://www.facebook.com/username/'),
      ),
      '#default_value' => variable_get('social_facebook', ''),
    );
    $form['social_detail']['social_linkedin'] = array(
      '#type' => 'textfield',
      '#title' => t('LinkedIn'),
      '#description' => t('Add your LinkedIn profile link here.'),
      '#attributes' => array(
        'placeholder' => t('https://www.linkedin.com/username/'),
      ),
      '#default_value' => variable_get('social_linkedin', ''),
    );
    $form['social_detail']['social_twitter'] = array(
      '#type' => 'textfield',
      '#title' => t('Twitter'),
      '#description' => t('Add your Twiiter profile link here.'),
      '#attributes' => array(
        'placeholder' => t('https://twitter.com/username/'),
      ),
      '#default_value' => variable_get('social_twitter', ''),
    );
    $form['social_detail']['social_youtube'] = array(
      '#type' => 'textfield',
      '#title' => t('Youtube'),
      '#description' => t('Add your Youtube profile link here.'),
      '#attributes' => array(
        'placeholder' => t('https://www.youtube.com/username/'),
      ),
      '#default_value' => variable_get('social_youtube', ''),
    );
    $form['social_detail']['social_google_plus'] = array(
      '#type' => 'textfield',
      '#title' => t('Google Plus'),
      '#description' => t('Add your Google Plus profile link here.'),
      '#attributes' => array(
        'placeholder' => t('https://www.plus.google.com/username/'),
      ),
      '#default_value' => variable_get('social_google_plus', ''),
    );
    $form['social_detail']['social_instagram'] = array(
      '#type' => 'textfield',
      '#title' => t('Instagram'),
      '#description' => t('Add your Instagram profile link here.'),
      '#attributes' => array(
        'placeholder' => t('https://www.instagram.com/username/'),
      ),
      '#default_value' => variable_get('social_instagram', ''),
    );

  }
  return $form;
}

/**
 * Implements hook_block_save()
 */
function social_contact_info_block_save($delta = '', $edit = array()) {

  if ($delta == 'social_contact_info') {
    // Contact title field.
    variable_set('contact_title', $edit['contact_title']);
    // Body editor field.
    variable_set('contact_address', $edit['contact_address']['value']);
    // Email field.
    variable_set('contact_email', $edit['contact_email']);
    // Phone field.
    variable_set('contact_phone', $edit['contact_phone']);
    // Mobile field.
    variable_set('contact_mobile', $edit['contact_mobile']);
    // FAX field.
    variable_set('contact_fax', $edit['contact_fax']);

    // Social title field.
    variable_set('social_title', $edit['social_title']);
    // Facebook field.
    variable_set('social_facebook', $edit['social_facebook']);
    // LinkedIn field.
    variable_set('social_linkedin', $edit['social_linkedin']);
    // Twitter field.
    variable_set('social_twitter', $edit['social_twitter']);
    // Youtube field.
    variable_set('social_youtube', $edit['social_youtube']);
    // Google Plus field.
    variable_set('social_google_plus', $edit['social_google_plus']);
    // Instagram field.
    variable_set('social_instagram', $edit['social_instagram']); 
  }
}

/**
 * Implements hook_block_view().
 */
function social_contact_info_block_view($delta = '') {
  $block = array();
  if ($delta == 'social_contact_info') {
    $block['subject'] = t('Contact Detail');
    $block['content'] = social_contact_info_theme_block_content();
  }
  return $block;
}

/**
 * Custom function for displying block information.
 */
function social_contact_info_theme_block_content() {
  $block = array();
  $block['contact_title'] = array(
    '#markup' => variable_get('contact_title', ''),
    '#prefix' => '<h3 class="contact-information-title">',
    '#suffix' => '</h3>',
  );
  $block['contact_address'] = array(
    '#markup' => variable_get('contact_address', '')
  );
  $block['contact_email'] = array(
    '#markup' => variable_get('contact_email', '')
  );
  $block['contact_phone'] = array(
    '#markup' => variable_get('contact_phone', '')
  );
  $block['contact_mobile'] = array(
    '#markup' => variable_get('contact_mobile', '')
  );
  $block['contact_fax'] = array(
    '#markup' => variable_get('contact_fax', '')
  );
  $block['social_title'] = array(
    '#markup' => variable_get('social_title', ''),
    '#prefix' => '<h3 class="social-information-title">',
    '#suffix' => '</h3>',
  );
  // $block['contact_address'] = array(
  //   '#markup' => variable_get('contact_address', '')
  // );
  // $block['contact_address'] = array(
  //   '#markup' => variable_get('contact_address', '')
  // );
  return $block;
}
